### ISSUE TITLE
Stops responding after a little idle time

### ISSUE THREAD

**Issue by vitobotta** [puma/puma#1184]
Hi, I'm having a problem with a new Rails 5 app with very little custom code and everything default where the puma server stops responding to requests after it has been idle for a little time. If I replace puma (3.6.2) with unicorn or I just comment it out in the Gemfile to use Webrick, it doesn't happen.

Any suggestion on how to investigate? I am not too familiar with how Puma works.

### Steps to reproduce

1) New Rails 5 app, everything default. Puma responds to requests if they keep coming

2) Leave the rails server idle with no requests for a little while

3) Send some requests again

### Expected behavior

Puma should continue responding to requests after having been idle.

### Actual behavior

Puma stops responding to requests which appear as "pending" e.g. in Chrome dev tools and nothing at all appears in the logs. 

### System configuration

**Ruby version**: 2.3.1p112
**Rails version**: 5.0.0.1

**Comment by vitobotta** [comment]
I have updated Rails to 5.0.1 but still the same. Very annoying :(
As said it's a new app but the only "non default" thing I have is a simple middleware for batch requests, see code below.

```ruby
class BatchRequests
  def initialize(app)
    @app = app
  end

  def call(env)
    if env["PATH_INFO"] == "/api/batch"
      request = ActionDispatch::Request.new(env.deep_dup)
      responses = JSON.parse(request[:requests]).map do |override|
        process_request(env.deep_dup, override)
      end
      [200, {"Content-Type" => "application/json"}, [{responses: responses}.to_json]]
    else     
      @app.call(env)
    end
  end

  private

    def process_request(env, override)
      path, query = override["url"].split("?")
      
      env["REQUEST_METHOD"] = override["method"]
      env["PATH_INFO"] = path
      env["QUERY_STRING"] = query
      env["rack.input"] = StringIO.new(override["body"].to_s)
      
      status, headers, body = @app.call(env)
      
      new_body = ""
      body.each { |line| new_body << line }
      body.close if body.respond_to?(:close)

      headers['Content-Length'] = new_body.length.to_s

      {status: status, headers: headers, body: new_body}
    end
end
```

**Comment by vitobotta** [comment]
Just tried with Passenger, and also with it I see no problems. So far it happens with Puma only.

**Comment by brateq** [comment]
Same problem here. Stage server hangs after couple minutes of idle time. Any ideas?

**Comment by allcentury** [comment]
Same issue, and an upgrade to 3.7.0 fixed it.  Until it's released, you can do this in your gemfile:

```ruby
gem 'puma', github: 'puma/puma', branch: '3.7.0'
```

**Comment by allcentury** [comment]
3.7.0 didn't fix it for me, I'm still running into issues

**Comment by nateberkopec** [comment]
Looks related to #1180

**Comment by dteoh** [comment]
I started experiencing this problem after updating to macOS 10.12.4. I am running Rails 5.0.2 with Ruby 2.3.1p112. I was initially running puma 3.6.2 + mysql2 0.4.4. Updating to 3.8.2 did not help. Also upgraded mysql2 gem to 0.4.5 but it did not help. I am using the default puma config that ships with Rails.

I tried debugging with lldb and dtruss, and can only see that a lot of threads are getting `psynch_cvwait = -1 Err#316`. Trying `rb_backtrace` was useless, either lldb gets stuck or I get:

```
(lldb) expression (void) rb_backtrace()
	from /Users/dteoh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.8.2/lib/puma/thread_pool.rb:236:in `block in start!'
	from /Users/dteoh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.8.2/lib/puma/thread_pool.rb:236:in `sleep'
```

My only workaround for now is to use the multiprocess mode with single threading.

**Comment by dteoh** [comment]
Okay, I finally got some hopefully useful backtrace from a crash when investigating through lldb. I removed the listen gem that shipped with Rails before doing this round of investigations, because that gem was causing me a lot of out of resource errors.

I walked through each thread in the list, printing its backtrace:

This was the result for every thread except for thread number 12:

```
(lldb) expression (void) rb_backtrace()
	from /Users/dteoh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.8.2/lib/puma/plugin/tmp_restart.rb:19:in `block in start'
	from /Users/dteoh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.8.2/lib/puma/plugin/tmp_restart.rb:19:in `sleep'
```

This is the thread list, after switching to thread 12:

```
(lldb) thread list
Process 11725 stopped
  thread #1: tid = 0x9b3de, 0x00007fffc3cc9bf2 libsystem_kernel.dylib`__psynch_cvwait + 10, queue = 'com.apple.main-thread'
  thread #2: tid = 0x9b3df, 0x00007fffc3ccb19e libsystem_kernel.dylib`poll + 10, name = 'ruby-timer-thr'
  thread #3: tid = 0x9b403, 0x00007fffc3cc9bf2 libsystem_kernel.dylib`__psynch_cvwait + 10, name = 'tmp_restart.rb*'
  thread #4: tid = 0x9b404, 0x00007fffc3cc9d42 libsystem_kernel.dylib`__pthread_kill + 10, name = 'thread_pool.rb*', stop reason = signal SIGABRT
  thread #5: tid = 0x9b405, 0x00007fffc3cc9bf2 libsystem_kernel.dylib`__psynch_cvwait + 10, name = 'thread_pool.rb*'
  thread #6: tid = 0x9b406, 0x00007fffc3cc9bf2 libsystem_kernel.dylib`__psynch_cvwait + 10, name = 'thread_pool.rb*'
  thread #7: tid = 0x9b407, 0x00007fffc3cc9bf2 libsystem_kernel.dylib`__psynch_cvwait + 10, name = 'thread_pool.rb*'
  thread #8: tid = 0x9b408, 0x00007fffc3cc9c22 libsystem_kernel.dylib`__psynch_mutexwait + 10, name = 'thread_pool.rb*'
  thread #9: tid = 0x9b409, 0x00007fffc3cc9eb6 libsystem_kernel.dylib`__select + 10, name = 'reactor.rb:151'
  thread #10: tid = 0x9b40a, 0x00007fffc3cc9bf2 libsystem_kernel.dylib`__psynch_cvwait + 10, name = 'thread_pool.rb*'
  thread #11: tid = 0x9b40b, 0x00007fffc3cc9bf2 libsystem_kernel.dylib`__psynch_cvwait + 10, name = 'thread_pool.rb*'
* thread #12: tid = 0x9b40c, 0x00007fffc3cc9eb6 libsystem_kernel.dylib`__select + 10, name = 'server.rb:325'
```

Running `rb_backtrace` on thread 12, I get the output seen in this gist: https://gist.github.com/dteoh/500e8330c53700dbb5ad4e12f1af6af3

I hope this will help in resolving this issue.

**Comment by GabKlein** [comment]
Same here but I'm on rails 4.2.7 ruby 2.3.1. 
I'm deploying my whole stack on docker swarm :

1) First connexion everything looks good.
2) Wait 10 to 15 minutes
3) Refresh
4) My service do not respond

The log console shows nothing more than:

```
Started GET "/v1/users/me" for 11.11.2.43 at 2017-05-22 07:45:00 +0000
```

On the docker instance:
A simple `curl localhost:3000` do not respond
Neither using telnet that at least connects then hangs

I tried Puma 3.6.0, 3.8.2, and also 2.16 so I don't think it is Puma related and I'm about to try with unicorn and passenger.
This issue describes the most what I have but if you can point me out to an other I would be glad.

**Comment by GabKlein** [comment]
Here the stack trace using Puma on the step 4:
https://gist.github.com/GabKlein/f08c03f0cb8dc6bff5ded564bafb8e96

**Comment by allcentury** [comment]
@GabKlein if you put Puma w/ one thread do you still see the issue?

**Comment by allcentury** [comment]
Appears to be the same as #1275 ?

**Comment by nateberkopec** [comment]
This is probably Rails autoloading (https://github.com/rails/rails/issues/27455). Anyone in this thread experiencing the issue, please report back if running Puma with one thread fixes the problem, *or* if you are experiencing this issue in production (i.e. config.eager_load = true).

**Comment by ypadlyak** [comment]
It does!

**Comment by GabKlein** [comment]
Ok, I found out what was going on and I hope that will help.

First of all and in my case, it's not a Puma issue. It's related to the docker swarm environment were client and server are on the same cluster and connexion are passing through the overlay network. 

Swarm max long live connexion are 900 seconds. Ruby libpg using system keepalived connexion settings by default, idle connexion after 900 seconds were closed by Swarm without notification to the client that do not try to connect again.

I fixed my issue by changing my client settings to never let connexions idle for more than 900. 
here my `database.yml`

```
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  timeout: 5000
  variables:
    tcp_keepalives_idle: 60
    tcp_keepalives_interval: 60
    tcp_keepalives_count: 100
```

**Comment by nateberkopec** [comment]
Okey dokey. This looks like Rails-related deadlocks.

If you are experiencing this issue, [use DebugLocks](http://api.rubyonrails.org/classes/ActionDispatch/DebugLocks.html) and report to Rails.

If you are *not using Rails*, this happens for you in production mode, or if this happens even if threads are set to 1, please open a new issue.

**Comment by simptive** [comment]
I'm using Rails 5.1.4 with Ruby 2.4.2. In my case, I found that Puma in development mode using same puma.rb which was modified for production actually.
Putting the following block in condition fixed the issue:

```
if ENV.fetch("RAILS_ENV") == 'production'
  app_dir = File.expand_path("../..", __FILE__)

  stdout_redirect "#{app_dir}/log/puma.stdout.log", "#{app_dir}/log/puma.stderr.log", true

  on_worker_boot do
    require "active_record"
    ActiveRecord::Base.connection.disconnect! rescue ActiveRecord::ConnectionNotEstablished
    ActiveRecord::Base.establish_connection(YAML.load_file("#{app_dir}/config/database.yml")[rails_env])
  end
end
```

**Comment by dottgonzo** [comment]
that's is crazy, rails is the only framework not working on my swarm! I've tried thin instead of puma (3.7), with same problems. I need to try in development mode but this is annoyng!!

**Comment by poc7667** [comment]
The problem is still on-going even I turned the earger loading -> true.

Here's my puma config and running the puma on ubuntu 14.
Any idea? or any alternative server could run a with nginx rever-proxy and rails

		bind "unix:///tmp/puma.app.sock"
		stdout_redirect "/tmp/puma.stdout.app.log", "/tmp/puma.stderr.app.log", true
		app_dir = File.expand_path("../..", __FILE__)
		workers 2 # because my linode only has 2 CPU cores
		threads 1,2
		pidfile "/tmp/puma.app.pid"
		#port        7617
		rails_env = "production"
		environment rails_env
		activate_control_app

		on_worker_boot do
		  require "mongoid"
		  Mongoid.load!("#{app_dir}/config/mongoid.yml", [rails_env])
		end

**Comment by ArielAleksandrus** [comment]
Same here. It works fine for like 10 minutes and then it suddenly freezes. Needs to restart server to make it work again. Someone please help!

**Comment by ArielAleksandrus** [comment]
@GabKlein this is an invalid config for me. Maybe because I'm using MySQL. Do you have any ideas?
