### ISSUE TITLE
RUBY_MN_THREADS=1 causes severe performance degredation

### ISSUE THREAD

**Issue by schneems** [puma/puma#3720]
Originally reported in https://github.com/puma/puma/issues/3715#issuecomment-3245560096
. 

It seems that `sleep` with the environment variable `RUBY_MN_THREADS=1` causes a performance degredation https://github.com/puma/puma/issues/3715#issuecomment-3245560096. 

This issue is for tracking the state of this regression so that we can link to it in a warning and we can remove the warning once the issue is fixed in upstream Ruby.

**Comment by p8** [comment]
Is this an issue for the Ruby bug tracker as well?

**Comment by schneems** [comment]
> Is this an issue for the Ruby bug tracker as well?

@p8 yes, eventually. Ideally I want to get a smaller [reproduction](https://www.codetriage.com/reproduction) that doesn't involve puma before reporting upstream.

@dentarg I tried reproducing this without Puma using only sleep, I'm not able to https://gist.github.com/schneems/883c1833d5ca48f80713b977728129fb. Perhaps there's some other condition such as a mix of "real" IO and sleep?

**Comment by schneems** [comment]
It might still be useful to share what we've got. I went ahead and filed an upstream reproduction: https://bugs.ruby-lang.org/issues/21560.

**Comment by dentarg** [comment]
I'll repeat my comment https://github.com/puma/puma/issues/3715#issuecomment-3247114128 because I think it is relevant 

> `echo 'silence_single_worker_warning; app { [200, {}, ["OK"]] }' | RUBY_MN_THREADS=1 ruby -Ilib bin/puma --config /dev/stdin --worker 1 --threads 1:1 --port 7777` is also instant for `hey -disable-keepalive -n 5000 -c 100 http://127.0.0.1:7777` if I remove this `sleep` (it is always `0.00015000000000000001` but I don't think it is the value that matters) https://github.com/puma/puma/blob/fa2458cf83a241b1fedc937bb56265e769dbe9ad/lib/puma/server.rb#L390-L391 ([thanks](https://github.com/puma/puma/pull/3678#discussion_r2310028332) @joshuay03)

**Comment by MSP-Greg** [comment]
@dentarg 

Try replacing:
https://github.com/puma/puma/blob/89a448e51b9ba22d46a7a6108fb4787623290dc2/lib/puma/server.rb#L389-L395

With:
```ruby
                  if @options[:workers] > 1
                    delay = 0.0001 * ((@reactor&.reactor_size || 0) + pool.busy_threads * 1.5)/max_flt
                    sleep delay
                  end
```

This should keep the behavior the same for when there is more than one worker.

**Comment by dentarg** [comment]
I can try that in a moment, but I'll share a thing first.

`hey -disable-keepalive -n 5000 -c 100 http://127.0.0.1:7777` is my `hey` command.

Against 1 worker 1 thread `echo 'silence_single_worker_warning; app { [200, {}, ["OK"]] }' | RUBY_MN_THREADS=1 ruby -Ilib bin/puma --config /dev/stdin --worker 1 --threads 1:1 --port 7777 is also instant for hey -disable-keepalive -n 5000 -c 100 http://127.0.0.1:7777` the `hey` command took ~55s.

Against 2 workers 1 thread `echo 'app { [200, {}, ["OK"]] }' | RUBY_MN_THREADS=1 ruby -Ilib bin/puma --config /dev/stdin --worker 2 --threads 1:1 --port 7777` the `hey` command took ~27s.

Against 10 workers 1 thread `echo 'app { [200, {}, ["OK"]] }' | RUBY_MN_THREADS=1 ruby -Ilib bin/puma --config /dev/stdin --worker 10 --threads 1:1 --port 7777` the `hey` command took ~6s.

Against 1 worker 10 threads `echo 'silence_single_worker_warning; app { [200, {}, ["OK"]] }' | RUBY_MN_THREADS=1 ruby -Ilib bin/puma --config /dev/stdin --worker 1 --threads 10:10 --port 7777` it was "instant" (`0.23s user 0.27s system 115% cpu 0.438 total`)

**Comment by dentarg** [comment]
I'm not sure what you are after with that change @MSP-Greg , I did it, started Puma with `--worker 1 --threads 1:1` and ran the `hey` command, it took ~54s.

**Comment by MSP-Greg** [comment]
You mentioned 'if I remove this sleep'.  The change should have the same effect?

**EDIT:** for `-w1`

**Comment by dentarg** [comment]
I made this change to Puma

```diff
$ git diff
diff --git a/lib/puma/server.rb b/lib/puma/server.rb
index a6c6260a..e999714e 100644
--- a/lib/puma/server.rb
+++ b/lib/puma/server.rb
@@ -388,7 +388,10 @@ module Puma
                 if pool.busy_threads >= @max_threads
                   if @clustered
                     delay = 0.0001 * ((@reactor&.reactor_size || 0) + pool.busy_threads * 1.5)/max_flt
+                    time_start = Process.clock_gettime(Process::CLOCK_MONOTONIC)
                     sleep delay
+                    running_time = Process.clock_gettime(Process::CLOCK_MONOTONIC) - time_start
+                    puts "sleep(#{delay}) took #{running_time}"
                   else
                     # use small sleep for busy single worker
                     sleep 0.0001
```

I start Puma like this `echo 'silence_single_worker_warning; app { [200, {}, ["OK"]] }' | RUBY_MN_THREADS=1 ruby -Ilib bin/puma --config /dev/stdin --worker 1 --threads 1:1 --port 7777 --log-requests`

If I run `hey -n 2 -c 2 http://127.0.0.1:7777` this is logged

```
[86716] 127.0.0.1 - - [04/Sep/2025:00:32:14 +0200] "GET / HTTP/1.1" 200 - 0.0001
sleep(0.00015000000000000001) took 0.010965999215841293
[86716] 127.0.0.1 - - [04/Sep/2025:00:32:14 +0200] "GET / HTTP/1.1" 200 - 0.0000
```

This doesn't reproduce with `-c 1` for hey (one connection). The first request also seems to take another branch in the Puma code. For example, with `-n 10` for hey, I see 9 `sleep ...` lines logged.

**Comment by dentarg** [comment]
> You mentioned 'if I remove this sleep'. The change should have the same effect?

Seems like it doesn't have https://github.com/puma/puma/issues/3720#issuecomment-3250879752

**Comment by MSP-Greg** [comment]
Confused.

`@options[:workers] > 1` is false for `-w1`.  This was the change I suggested, along with removing the `else` clause.  The change does not execute `sleep` for `-w1`.

`@clustered` is true for `-w1`.  This is the original code.  This executes `sleep` for `-w1`.

**Comment by dentarg** [comment]
I didn't remove the else, sorry :)

**Comment by dentarg** [comment]
Anyway, it reproduces with multiple workers too https://github.com/puma/puma/issues/3720#issuecomment-3250871753

**Comment by MSP-Greg** [comment]
@dentarg

I'm confused.  I added the patch as above.
```
echo 'app { [200, {}, ["OK"]] }' | RUBY_MN_THREADS=1 bundle exec puma --config /dev/stdin -w1 -t1:1 --port 7777

hey -n 5000 -c 100 -cpus 10 http://127.0.0.1:7777
Summary:
  Total:        0.3954 secs
  Slowest:      0.1589 secs
  Fastest:      0.0003 secs
  Average:      0.0070 secs
  Requests/sec: 12646.4215

hey -n 5000 -c 100 -cpus 10 -disable-keepalive http://127.0.0.1:7777
Summary:
  Total:        0.8651 secs
  Slowest:      0.0271 secs
  Fastest:      0.0012 secs
  Average:      0.0172 secs
  Requests/sec: 5779.6708
```
Similar results with the below (no `-w1`):
```
echo 'app { [200, {}, ["OK"]] }' | RUBY_MN_THREADS=1 bundle exec puma --config /dev/stdin -t1:1 --port 7777
```

**Comment by schneems** [comment]
So: sleep seems related. But my gist posted above didn’t demonstrate that sleep by itself is a problem. So what new theories do we have to try to reduce the reproduction?

My theory stated above is that possibly it needs a mix of operations that would otherwise trigger releasing the GIL. Puma has a lot of IO (nio4r, pipes, socket reads, etc.) and pseudo IO (stringIO manipulation). I’m not sure what a good approach to determining what mix is causing the interaction.

Another hunch is that it could be related to mutexes as my analysis on reported in #3715 showed significant time spent in Mutex#synchronize. If someone removes mutex calls (and ignore the incorrect software behavior), if this is THE interacting problem then I would expect performance to jump through the roof.

**Comment by MSP-Greg** [comment]
> So: sleep seems related.

Speaking of sleep, I just shut down all Puma work.

> showed significant time spent in Mutex#synchronize

Another rabbit hole I've peered into is replacing a lot of the ThreadPool logic using mutexes, etc with code using queues, as there is a fair bit of `+= 1` and `-=1`.  I did start on that recently.  Then, the idea of controlling the select/accept loop in `Server#handle_servers` with a queue.  Not quite far enough along, but some quick testing shows it equal to or slightly better than 7.0.0 depending on the test...

**Comment by schneems** [comment]
I’ve wondered about removing some of the mutexes as well. I think the two options would be not caching counts (in the case of the @todo size), or having a single object that queues increment or decrement operations. I’ve not benchmarked either.

**Comment by dentarg** [comment]
So we should avoid [the `sleep`](https://github.com/puma/puma/blob/89a448e51b9ba22d46a7a6108fb4787623290dc2/lib/puma/server.rb#L389-L395) for a single worker

**Comment by schneems** [comment]
> So we should avoid [the sleep](https://github.com/puma/puma/blob/89a448e51b9ba22d46a7a6108fb4787623290dc2/lib/puma/server.rb#L389-L395) for a single worker

#3723 is addressing that. It's true that it's not needed, but I've not validated that removing that sleep fixes the RUBY_MN_THREADS=1 perf issue.

**Comment by dentarg** [comment]
> I've not validated that removing that sleep fixes the RUBY_MN_THREADS=1 perf issue.

From https://bugs.ruby-lang.org/issues/21560 it sounds like the issue goes beyond `sleep` (all scheduling)

I don't think Puma is doing anything wrong but perhaps we should keep this open until the Ruby bug has been addressed?

**Comment by schneems** [comment]
The warning that puma emits links to this issue. We should keep this open until people can safely ignore that warning.

**Comment by amuta** [comment]
This should have been fixed by https://github.com/ruby/ruby/pull/14952

**Comment by schneems** [comment]
Thanks!

Can someone validate the original repro with puma is comparable to running without the env set?

The warning message links to this issue. We should scope it to not fire gated on Ruby version (I understand that next release is either 3.5 or 4.0). Once it is released and update the issue title to make it clear that older versions still have this problem.

**Comment by MSP-Greg** [comment]
I just ran this with Ruby before and after @amuta's commit.  That's a serious increase in performance, not expected.  Also, see https://bugs.ruby-lang.org/issues/21560#note-7, which also showed an increase.

Note the `+MN` added to `RUBY_DESCRIPTION`.

This is using two desktops, one (WSL2/Ubuntu) running Puma, and an iMac running the hey commands.

```
ruby 3.5.0dev (2025-10-30T17:44:35Z master 9b1894690f) +PRISM [x86_64-linux]
  Puma: -w16 -t3:3  dly 0.001                                    Branch: main
Mult    RPS     50%      99%    ───────────────────── Hey Command ─────────────────────
6.00  12342   0.0224   0.0372   hey -c 288 -n 28800  http://10.31.33.2:40001/sleep0.001
4.00  12756   0.0142   0.0251   hey -c 192 -n 19200  http://10.31.33.2:40001/sleep0.001
3.00  12977   0.0104   0.0170   hey -c 144 -n 14400  http://10.31.33.2:40001/sleep0.001
2.00  13418   0.0063   0.0114   hey -c  96 -n  9600  http://10.31.33.2:40001/sleep0.001
1.50  12563   0.0054   0.0087   hey -c  72 -n  7200  http://10.31.33.2:40001/sleep0.001
1.00  11135   0.0039   0.0086   hey -c  48 -n  4800  http://10.31.33.2:40001/sleep0.001
0.50  10856   0.0021   0.0037   hey -c  24 -n  2400  http://10.31.33.2:40001/sleep0.001


ruby 3.5.0dev (2025-10-31T02:30:05Z master 5b2707f39b) +MN +PRISM [x86_64-linux]
  Puma: -w16 -t3:3  dly 0.001                                    Branch: main
Mult    RPS     50%      99%    ───────────────────── Hey Command ─────────────────────
6.00  22552   0.0121   0.0230   hey -c 288 -n 28800  http://10.31.33.2:40001/sleep0.001
4.00  22396   0.0081   0.0158   hey -c 192 -n 19200  http://10.31.33.2:40001/sleep0.001
3.00  22058   0.0056   0.0134   hey -c 144 -n 14400  http://10.31.33.2:40001/sleep0.001
2.00  22164   0.0038   0.0093   hey -c  96 -n  9600  http://10.31.33.2:40001/sleep0.001
1.50  21429   0.0030   0.0070   hey -c  72 -n  7200  http://10.31.33.2:40001/sleep0.001
1.00  19239   0.0022   0.0053   hey -c  48 -n  4800  http://10.31.33.2:40001/sleep0.001
0.50  14573   0.0015   0.0034   hey -c  24 -n  2400  http://10.31.33.2:40001/sleep0.001
```

**Comment by schneems** [comment]
That is very unexpected. Maybe we change the warning from “turn it off” to “turn it on” in 3.5/4.0?

**Comment by MSP-Greg** [comment]
> That is very unexpected.

Agreed.  I just posted in ruby about whether the fix will be backported to Ruby 3.3 & 3.4.  3.4 is listed as 'required', 3.3 isn't, and the issue was closed.  I'm checking Ruby 3.2 soon, I doubt it will have the problem.

**Comment by p8** [comment]
Enabling RUBY_MN_THREADS on 4.0-rc results in the following errors on the TechEmpower rack benchmarks.
Even when running the `json` test.

```
rack: [8] ! Terminating timed out worker (Worker 4 failed to check in within 60 seconds): 23
rack: [8] - Worker 4 (PID: 81) booted in 0.0s, phase: 0
rack: [8] ! Terminating timed out worker (Worker 6 failed to check in within 60 seconds): 29
rack: [8] ! Terminating timed out worker (Worker 7 failed to check in within 60 seconds): 32
rack: [8] - Worker 7 (PID: 87) booted in 0.03s, phase: 0
rack: [8] - Worker 6 (PID: 91) booted in 0.0s, phase: 0
```

So the warning probably still makes sense?

**Comment by dentarg** [comment]
It would be good to find out why the workers timed out. Are there any more logs @p8? Can we reproduce that worker timeout outside the benchmark?

**Comment by p8** [comment]
@dentarg It seems this issue has been fixed on the latest Puma and Ruby.

On the latest run I enabled `RUBY_MN_THREADS` again and upgraded Ruby from 4.0-rc to 4.0.
With `RUBY_MN_THREADS=1` shows a significant improvement (~30%):

## Before

<img width="1172" height="212" alt="Image" src="https://github.com/user-attachments/assets/fbc08229-25df-45c5-9433-a4ab5e40750b" />

https://www.techempower.com/benchmarks/#section=test&runid=125d9074-7092-41c0-8545-5df64cb5302b&l=zik0zj-p9z&w=zik0zj-zik0zj-zik0xr-zik0zj-3j&c=d&f=zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-hra0hn-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-cn3

## After

<img width="1176" height="213" alt="Image" src="https://github.com/user-attachments/assets/807daa88-28a1-416a-9361-54c4e79980fd" />

https://www.techempower.com/benchmarks/#section=test&runid=f59a9c0c-19a4-4dab-b0f5-f8f175091bfa&test=fortune&l=zik0zj-p9z&w=zik0zj-zik0zj-zik0xr-zik0zj-3j&c=d&f=zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-hra0hn-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-cn3

Another interesting thing is that the difference between MySQL (with `trilogy`) and PostgreSQL (with `pg`) is a lot smaller now.

For the next run I've enabled it for all benchmarks running with Puma (so also for Sinatra and Rails).

**Comment by p8** [comment]
On the latest run I enabled RUBY_MN_THREADS for Rails and Sinatra.
With RUBY_MN_THREADS=1 shows a significant improvement (~15%).
Some notes:
- "rails [puma, mysql]" doesn't have it enabled yet so it shows no improvement
- "sinatra [puma, postgres]" is scoring badly because of misconfiguration.

## Before

<img width="1144" height="194" alt="Image" src="https://github.com/user-attachments/assets/b26fb55e-1e9b-43c4-9ca9-e46f1d2197a6" />

https://www.techempower.com/benchmarks/#section=test&runid=a12d8f43-58bc-4ad1-9277-aa5ab294c10b&l=zik0zj-p9y&w=zik0zj-zik0zj-zik0xr-zik0zj-3j&f=zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0vz-yyku7z-zik0zj-zik0zj-zik0zj-zik0zj-pa7

## After

<img width="1143" height="202" alt="Image" src="https://github.com/user-attachments/assets/96d8d7c5-4081-43a0-8c2c-f4d9173bf99e" />

https://www.techempower.com/benchmarks/#section=test&runid=acc1ad82-ae2c-4d1d-a600-c7ff9d0c5917&l=zik0zj-p9y&w=zik0zj-zik0zj-zik0xr-zik0zj-3j&f=zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0vz-yyku7z-zik0zj-zik0zj-zik0zj-zik0zj-pa7

I'm wondering if the performance improvement is related to an [MN_THREADS bug](https://bugs.ruby-lang.org/issues/21836) where `sleep(0.0001)` returns too fast.
