### ISSUE TITLE
Configuration file when booted through `rails server`

### ISSUE THREAD

**Issue by nanaya** [puma/puma#512]
Currently, booting puma through `rails server` will start it using thread configuration of `0:16` which breaks `binding_of_caller` thanks to thread difference between requests. I couldn't find way to force `1:1` without calling `puma` directly which in turn changes logging behavior. It would be nice if the configuration file (`config/puma.rb` / `config/puma/#{ENV['RACK_ENV']}.rb`) is also loaded when called through `rails server`.

**Comment by jeremyhaile** [comment]
@evanphx Why not? Isn't that something that should be supported?

**Comment by jeremyhaile** [comment]
The problem I'm having is that if you start it as puma, then the logging doesn't operate like `rails server` But if you start it as `rails server puma` then it doesn't load our configuration, which includes reading environment variables, and `on_worker_boot` callbacks. It seems like the inability to load the configuration file makes `rails server puma` unusable for many projects. 

Is that true? If it is true, perhaps we should update the README to reflect this.

**Comment by vemv** [comment]
I second @jeremyhaile's question - why not? Isn't it something worthy of working on?

It's not attractive having to use an alien command (`puma`) instead of transparently integrating into `rails server`, as Thin and others do.

**Comment by evanphx** [comment]
So, here is the reason I don't want to enhance this route: when launched via `rails server`, puma doesn't control the process from the start. This means that things like hot restart, etc won't work correctly. 

Additionally, I have no clue what has already been loaded so I can't reliably fork, so cluster mode is a no-go.

It's just a whole lot of additional headaches with very little upside.

**Comment by evanphx** [comment]
@jeremyhaile As for the logging, I've talked with rails-core about that and I need to discuss with them again. We should solve that problem instead. /cc @tenderlove

**Comment by vemv** [comment]
@evanphx nice, sounds fair enough. Thanks for the answer!

**Comment by edogawaconan** [comment]
looking again, I noticed that the logging behavior can just be fixed by explicitly setting logger output to `STDOUT` (which is what commonly suggested for production as well). Though in this case puma's logger timestamp makes the output a bit noisier than simply from `rails server`.

**Comment by vemv** [comment]
@edogawaconan probably you can assign a `::Logger::Formatter.new` (Rails' production logger formatter) somewhere

**Comment by edogawaconan** [comment]
It's still the same noisy format. I haven't looked into log formatting enough to fix this.

Also it makes rails console gives duplicate output:

```
### default logger
irb(main):001:0> Post.count
   (43.5ms)  SELECT COUNT(*) FROM "posts"
=> 298121

### STDOUT logger
irb(main):002:0> Post.count
   (48.7ms)  SELECT COUNT(*) FROM "posts"
D, [2015-03-09T14:11:59.271945 #15239] DEBUG -- :    (48.7ms)  SELECT COUNT(*) FROM "posts"
=> 298121
irb(main):003:0>

```

(though practically speaking, I've returned to using plain webrick for development so this issue doesn't affect me anymore)

**Comment by jrochkind** [comment]
I'm not having luck googling, any progress on this in other issues or other places?

Puma with multiple threads/workers messes up my byebug use, which is crucial for my development workflow. 

Is there any way to set puma configuration in `rails server` dev mode?  Or any way to tell rails to go back to using webrick even if puma is in the gemfile? Or other solutions?

**Comment by vemv** [comment]
@jrochkind in your Gemfile, wrap your `puma` declaration within a `group: :production,  :statging do` block

**Comment by nanaya** [comment]
`require: false` should also work assuming you're launching `puma` directly through its command instead of `rails server`.

**Comment by jrochkind** [comment]
Thanks friends. 

Huh, so if Rails 5 is supposed to read the config... a) someone should prob close this issue, so it's more clear to someone googling like I was, and b) I wonder why it's not for me. 

Not working for me. puma 3.6.0. rails 5.0.1.  Config changes to workers/threads in `./config/puma.rb` have no effect on `rails server`. Indeed, even if I add a `raise` or syntax error in `./config/puma.rb`, it is not triggered, the `puma.rb` does not seem to be loaded at all from `rails server` -- even though the puma startup messages _are_ in the console. 

This is an app that has been upgraded many times and used to be rails4, sometimes that matters because some important piece of information was left out of initializers or config files, but I can't find or think of one here. 

Not really sure where to go from here.

**Comment by jrochkind** [comment]
oops, this issue _was_ closed, but closed with a "won't fix", where in fact it was fixed? Okay then...

**Comment by nanaya** [comment]
This is how my app looks like. Note threads number.

```
$ RAILS_MAX_THREADS=17 bundle exec rails s
/home/edho/apps/ruby24/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/home/edho/apps/ruby24/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
=> Booting Puma
=> Rails 5.0.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
/home/edho/apps/ruby24/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated
Puma starting in single mode...
* Version 3.6.2 (ruby 2.4.0-p0), codename: Sleepy Sunday Serenity
* Min threads: 17, max threads: 17
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop
```

[config file](https://bitbucket.org/nanaya1/zeropaste/src/default/config/puma.rb) (default from rails 5 iirc).

**Comment by jrochkind** [comment]
I have an older config file, [gisted here](https://gist.github.com/jrochkind/2b2dd748ba5b489f91895c1dadeda233) which uses `PUMA_MAX_THREADS` instead of `RAILS_MAX_THREADS`. 

However, no matter what I set `PUMA_MAX_THREADS` to (or `RAILS_MAX_THREADS`), or what I set `PUMA_WORKERS` to, I have one worker and 2 threads, I can get neither more nor less. Not even by hard-coding them in the `./config/puma.rb`. Pretty certain the `./config/puma.rb` is not being used. 

~~~
[35547] Puma starting in cluster mode...
[35547] * Version 3.6.0 (ruby 2.3.0-p0), codename: Sleepy Sunday Serenity
[35547] * Min threads: 2, max threads: 2
[35547] * Environment: development
[35547] * Process workers: 1
[35547] * Preloading application
[35547] * Listening on tcp://localhost:3000
~~~

**Comment by nateberkopec** [comment]
@jrochkind I think what you're seeing is #1200.

**Comment by jrochkind** [comment]
@nateberkopec I'm not sure, that problem seems to be about options in config/puma.rb overwriting other options? My problem is kind of the reverse, options in config/puma.rb seem to be getting ignored, the entire config/puma.rb file seems to have no effect. 

But I'll try it out when 3.7.1 is released.

**Comment by nateberkopec** [comment]
@jrochkind Give it a shot against master, tell me what happens.

**Comment by jrochkind** [comment]
So, in a different app that does not exhibit the problem, changes i make in `config/puma.rb` are reflected in puma startup logs when running `rails server`, and additionally if I put a `byebug` in `config/puma.rb`, then I do get a breakpoint triggered when running `rails server`.  All as expected and desired. 

In the problematic app -- and of course I don't know what the difference is, but the problematic app is a much older app that has been upgraded through various versions of rails and puma but is currently rails 5.0.1 -- changes I make in `config/puma.rb` are _not_ reflected in puma startup logs on `rails server`, and additionally a `byebug` in `config/puma.rb` does _not_ trigger a breakpoint. It's as if `config/puma.rb` is not being loaded at all. 

In the problematic app (Rails 5.0.1), this problem exhibits with puma: 3.6.0, 3.6.2, 3.7.0 _and_ master at 6b96a9

**Comment by nateberkopec** [comment]
OK, weird. Obviously I'm going to need you to figure out what that difference is, but it's clearly not the issue I mentioned.

**Comment by jrochkind** [comment]
Ugh, ignore me. Thanks for the replies, my fault. I got to debugging and discovered I had a config/puma/development.rb, so that was being used instead of config/puma.rb.  I didn't even know that was a puma feature. Some previous developer on this project must  left it there. Sorry, thanks!
