### ISSUE TITLE
Puma says "Address already in use"

### ISSUE THREAD

**Issue by eliduke** [puma/puma#516]
I read through a long thread of issue #73 and #193 hoping to find a solution. It seems as though it was addressed for some people with some previous releases, but I'm having the problem again. Just wanted to put this out there and see if anyone else is still having this problem.

This is what I get when I run 'foreman start' from my app root.

```
22:01:58 web.1  | started with pid 33702
22:01:59 web.1  | [33702] Puma starting in cluster mode...
22:01:59 web.1  | [33702] * Version 2.8.1 (ruby 2.1.0-p0), codename: Sir Edmund Percival Hillary
22:01:59 web.1  | [33702] * Min threads: 1, max threads: 16
22:01:59 web.1  | [33702] * Environment: development
22:01:59 web.1  | [33702] * Process workers: 3
22:01:59 web.1  | [33702] * Preloading application
22:02:01 web.1  | [33702] * Listening on tcp://0.0.0.0:5000
22:02:01 web.1  | /Users/eli/.rvm/gems/ruby-2.1.0/gems/puma-2.8.1/lib/puma/binder.rb:195:in `initialize': Address already in use - bind(2) for "0.0.0.0" port 5000 (Errno::EADDRINUSE)
22:02:01 web.1  |   from /Users/eli/.rvm/gems/ruby-2.1.0/gems/puma-2.8.1/lib/puma/binder.rb:195:in `new'
22:02:01 web.1  |   from /Users/eli/.rvm/gems/ruby-2.1.0/gems/puma-2.8.1/lib/puma/binder.rb:195:in `add_tcp_listener'
22:02:01 web.1  |   from /Users/eli/.rvm/gems/ruby-2.1.0/gems/puma-2.8.1/lib/puma/binder.rb:96:in `block in parse'
22:02:01 web.1  |   from /Users/eli/.rvm/gems/ruby-2.1.0/gems/puma-2.8.1/lib/puma/binder.rb:82:in `each'
22:02:01 web.1  |   from /Users/eli/.rvm/gems/ruby-2.1.0/gems/puma-2.8.1/lib/puma/binder.rb:82:in `parse'
22:02:01 web.1  |   from /Users/eli/.rvm/gems/ruby-2.1.0/gems/puma-2.8.1/lib/puma/runner.rb:119:in `load_and_bind'
22:02:01 web.1  |   from /Users/eli/.rvm/gems/ruby-2.1.0/gems/puma-2.8.1/lib/puma/cluster.rb:275:in `run'
22:02:01 web.1  |   from /Users/eli/.rvm/gems/ruby-2.1.0/gems/puma-2.8.1/lib/puma/cli.rb:506:in `run'
22:02:01 web.1  |   from /Users/eli/.rvm/gems/ruby-2.1.0/gems/puma-2.8.1/bin/puma:10:in `<top (required)>'
22:02:01 web.1  |   from /Users/eli/.rvm/gems/ruby-2.1.0/bin/puma:23:in `load'
22:02:01 web.1  |   from /Users/eli/.rvm/gems/ruby-2.1.0/bin/puma:23:in `<main>'
22:02:01 web.1  |   from /Users/eli/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
22:02:01 web.1  |   from /Users/eli/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'
22:02:01 web.1  | exited with code 1
22:02:01 system | sending SIGTERM to all processes
SIGTERM received
```

**Comment by LaurMo** [comment]
Foreman is still doing this error for me - how did ya'll solve it?

**Comment by eliduke** [comment]
@LaurMo I don't know if I ever fully solved it, but it wasn't happening every time. I haven't been using Foreman much lately, so I'm a little out of the loop on that. Are you having the same exact error that I was having? Maybe we could post this error as an issue with Foreman. Thoughts?

**Comment by mfpiccolo** [comment]
This is happening for me when I control c to quit foreman.  I then have to use `lsof -i :5000` and `sudo kill -9 <pid>` to kill the process if I want to run foreman again.

**Comment by LaurMo** [comment]
^ That's what I do as well.  Hoping this could somehow get fixed either on the foreman or puma side.

**Comment by evanphx** [comment]
It sounds like foreman isn't telling puma to quit properly. I'll try to load it up and see what's it's doing. Could someone post the `Procfile` they're using?

**Comment by mfpiccolo** [comment]
Procfile:

```
web: puma --config config/puma.rb
worker1: QUEUE=1 bundle exec rake jobs:work
worker2: QUEUE=2 bundle exec rake jobs:work
worker3: QUEUE=3 bundle exec rake jobs:work
```

**Comment by evanphx** [comment]
Could you post your config/puma.rb then too?

**Comment by mfpiccolo** [comment]
```
workers Integer(ENV['PUMA_WORKERS'] || 1)

threads Integer(ENV['MIN_THREADS'] || 2),
        Integer(ENV['MAX_THREADS'] || 2)

preload_app!

rackup DefaultRackup

# Heroku will set this when the web process boots up
port ENV['PORT'] || 3000

# On Heroku this will be set to 'production' by default
environment ENV['RACK_ENV'] || 'development'

on_worker_boot do
  ActiveRecord::Base.establish_connection
end
```

**Comment by gunosk129** [comment]
+1

**Comment by askl56** [comment]
Hmm seems like this issue is still occuring

**Comment by evanphx** [comment]
This should be fixed in the latest release, please update and try again.

**Comment by Dorian** [comment]
It happens so often I made a script for it:

```
#!/usr/bin/env ruby

port = ARGV.first || 3000

# Just to get sudo
system("sudo echo kill-server-on #{port}")

pid = `sudo lsof -iTCP -sTCP:LISTEN -n -P | grep #{port} | awk '{ print $2 }' | head -n 1`.strip
puts "PID: #{pid}"
`kill -9 #{pid}` unless pid.empty?
```

**Comment by lightbe** [comment]
@Dorian I'm having a consistent problem with puma in one of my Rails apps on my Mac Mini server and in Heroku. I would like to implement your script. How/where are you executing this script?

**Comment by Dorian** [comment]
@lightbe just `kill-server-on 3000` for instance to kill the process that is listening on port 3000 (puma in this case)

I'm gonna add my scripts to https://github.com/Dorian/bin at some point this week

**Comment by eliduke** [comment]
This still happens sometimes. Still can't figure out what conditions cause it though.

**Comment by brendonrapp** [comment]
It happens so often. I think I'm going to start using Dorian's script, I'm tired of it.

**Comment by MassMadankumar** [comment]
root@instance-2:/mnt/zapstore.com/shopifyapp/zap# rails s
=> Booting Puma
=> Rails 5.1.4 application starting in development
=> Run `rails server -h` for more startup options
A server is already running. Check /mnt/zapstore.com/shopifyapp/zap/tmp/pids/server.pid.
Exiting

**Comment by pailoro** [comment]
This code will automate the process of fixing it for you https://github.com/pailoro/rails_server_killer

**Comment by brendonrapp** [comment]
Still an ongoing issue.

**Comment by mcandre** [comment]
Unfortunately, I am also getting `Address in use - bind(2) for "0.0.0.0" port 3030 (Errno::EADDRINUSE)` for my Puma deployment in Docker.

**Comment by fighella** [comment]
For anyone that has issues with Port 5000 

https://developer.apple.com/forums/thread/682332

**Comment by steady-daddy** [comment]
As stated in the link shared above, this is due to the AirPlay receiver. Quick fix is to disable it as explained here: https://twissmueller.medium.com/resolving-the-problem-of-port-5000-already-being-in-use-dd2fe4bad0be

I stumbled upon this issue while trying to run Puma via foreman on a Rails app.
