### ISSUE TITLE
Puma silently crashed

### ISSUE THREAD

**Issue by nateless** [puma/puma#554]
Puma silently crashed, there's no error at all, puma_error.log, puma_access.log as well as production.log are empty. nginx log is also fine before crash. Here is capistrano configuration options: 

```
set :puma_threads, [0, 16]
set :puma_workers, 0
set :puma_worker_timeout, nil
set :puma_init_active_record, true
set :puma_preload_app, true
```

It can work days before crash, I've had 3 crashes for the past two weeks. One was within 20h from start, its brand new server with 64GB RAM, ubuntu 14, we don't have a lot of users ~ 300 per day, however we have websocket streaming with tubesock.

We also use rollbar for external logging and it's also empty. We don't see any spikes on CPU\Memory usage during crashes.

We use Puma 2.8.2, Rails 4.1.4

Is there any way to turn more detailed logging, or find the problem?

**Comment by wuboy0307** [comment]
+1 here. rails 4.1.8.
I also use websocket-rails with standalone thin server. Is websocket an issue? @nateless also has websocket with tubesock.

**Comment by foi** [comment]
Hello! I have same trouble. I tried varous rubies, web servers. We are using redmine app with puma with https unsigned certificate. When i trying to open redmine app from home (redmine server in long distance from me) it's hangs (in home i "slow client", poor quality 4G with a lot of packetloss and latency), not every time, but 25% of initial request hangs puma, puma 'https' get unacessible even from localhost. Recently i find Rack::Timeout gem and scenario for cope with problem https://devcenter.heroku.com/articles/request-timeout. I hope it will help me. Otherwise, i will be here again )

**Comment by sheharyarn** [comment]
Same issue, nothing of importance in the logs. Using `Ruby 2.2`, `Rails 4.2` and `Puma 2.11.1`.

**Comment by evanphx** [comment]
@sheharyarn when does it crash? after it's been running a while? At boot?

**Comment by sheharyarn** [comment]
@evanphx After a few hours of running. Here are some graphs from my Digital Ocean Droplet:

![screen shot 2015-04-07 at 4 21 06 pm](https://cloud.githubusercontent.com/assets/2355108/7040586/2ed21720-ddea-11e4-98a4-0feabe85d7c4.png)
![screen shot 2015-04-07 at 4 21 18 pm](https://cloud.githubusercontent.com/assets/2355108/7040587/2ed84c4e-ddea-11e4-824a-8cf3cf595944.png)

It crashes every few hours, then I get a notification from [Uptime Robot](http://uptimerobot.com/) and I start Puma again. There's nothing of importance in the Puma Logs (well, at least that's what I think). Puma Access log  has occasional `IOErrors` but I think it's related to the External Binary I'm using, and Pume Error log only shows timestamps of when the server starts.

Puma.error.log:

```
=== puma startup: 2015-04-07 00:12:08 -0400 ===
* Listening on unix:///home/deploy/apps/kholopk/shared/tmp/sockets/kholopk-puma.sock
=== puma startup: 2015-04-07 02:19:16 -0400 ===
* Listening on unix:///home/deploy/apps/kholopk/shared/tmp/sockets/kholopk-puma.sock
=== puma startup: 2015-04-07 04:15:19 -0400 ===
* Listening on unix:///home/deploy/apps/kholopk/shared/tmp/sockets/kholopk-puma.sock
=== puma startup: 2015-04-07 06:16:15 -0400 ===
* Listening on unix:///home/deploy/apps/kholopk/shared/tmp/sockets/kholopk-puma.sock
```

I even tried removing the [PumaWorkerKiller Gem](https://github.com/schneems/puma_worker_killer/) and downgrading `Puma` to `2.7.1` (like @moofish32 said), but nothing worked. I don't have a clue what to do.

Could this be an issue with heavy user traffic? Because I have another droplet that was set up almost the exact same way, but it doesn't crash and it has almost 0 traffic, on the other hand this droplet gets around >1k Page Views a day. Both of these droplets were set up [this way](https://coderwall.com/p/ttrhow).

**Comment by MisterFine1** [comment]
@sheharyarn I work with moofish32.  We've been trying to figure this out but don't have a reliable way to re-create it.  It sounds like you do.  Have you been able to look in system logs or other logs to look for out of memory, security or any other related events that may have occurred at the same time?  Can you identify any pattern of the type of request it's serving, database being persisted to, etc. for any application layer patterns?

Lastly, could you (or have you) tried doing detailed logging/tracing (TracePoint) to try and identify any common patterns or locations in the code that are being accessed prior to failure?

Sorry for the lengthy/open questions... we're just trying hard to look for anything that might help clear this up.  It's a serious problem for us.

**Comment by evanphx** [comment]
@sheharyarn @MisterFine1 The overall problem with these issues is that there is a 90% chance that it's something within your app. Running out of database connections, deadlocking in some non-threadsafe code, etc. Within puma itself, the only thing that would cause an eventual outage is really a memory leak that causes the system to grind to a halt. While there are people reporting a memory leak, I still am unable to reproduce it and my theory is that it's actually something else within Ruby that is causing the problem.

**Comment by evanphx** [comment]
@sheharyarn Are you using workers? Do all the workers crash too? I'm wondering if maybe a gem you're using is crashing and bringing the whole process down.

**Comment by MisterFine1** [comment]
@evanphx... I hope you are right that is something within our app.  We use jruby exclusively, and haven't seen any memory leaks (we monitor the jvm).  Our app does do some it's own internal threading, using Akka as the actor system.  

I'm a little confused by your idea that this failure could be caused by a deadlock.  If it were, wouldn't the symptom be long delayed or never-ending requests?  We are simply seeing Puma disappear without any logging.  It just vanishes.  I'm not clear how that would be from a deadlock.

**Comment by evanphx** [comment]
@MisterFine1 Totally true, a deadlock wouldn't cause it to just disappear like that. Since you're not using workers, if it just disappears like that, then it's a JVM crash I assume? Are you using `daemonize`? If so, can you turn it off and see you can get any more info from the output? The `daemonize` code for JRuby is squirrelly due to the JVM so we might get more data that way.

**Comment by sheharyarn** [comment]
Okay, I've looked into it a bit more, it seems that the issue was with the Memory Leaks in `Ruby 2.2.0` that existed in `Ruby 2.1.x`. Around 10 hours ago, I downgraded to `ruby-2.0.0-p598` and Puma hasn't crashed since, so I'm hoping that the issue has been resolved (Previously it was crashing every 2-3 hours).

I'm going to keep an eye on it for another few days, and will report back. Thanks for your input!

Sources:
 - Stackoverflow: [Does Ruby 2.2 have Memory Issues?](http://stackoverflow.com/questions/27653207/does-ruby-2-2-have-memory-issues-on-heroku)
 - Ruby Bug Tracker: [#10686 - Memory leaking from torture test of symbol GC](https://bugs.ruby-lang.org/issues/10686)
 - Official Ruby Blog: [Ruby 2.2.1 Released](https://www.ruby-lang.org/en/news/2015/03/03/ruby-2-2-1-released/)

**Comment by sheharyarn** [comment]
@evanphx @MisterFine1 I don't think I might be able to report much because I'm not much of an expert. I also don't think the issue is with any other gems. I also checked my `/var/log/syslog`, and the last entry in it was from a month ago when I first created my droplet.

My app uses `Mongoid`, but I'm not writing anything to the DB at the moment, because all my app does is display some links to Youtube Videos that I get from the Youtube API I'm consuming. I'm also calling an external program [`youtube_dl`](https://github.com/rg3/youtube-dl/) using the `system` method for a JSON dump for some video information that I do not get using the official API.

This is my Gemfile:

```ruby
source 'https://rubygems.org'

ruby '2.0.0' 
gem  'rails', '4.2.0'

group :assets do
    gem 'sass-rails',       '~> 5.0'
    gem 'coffee-rails',     '~> 4.1.0'
    gem 'uglifier',         '>= 1.3.0'
end

group :development do
    gem 'spring'
    gem 'byebug'
    gem 'web-console',      '~> 2.0'

    gem 'capistrano',         require: false
    gem 'capistrano-rvm',     require: false
    gem 'capistrano-rails',   require: false
    gem 'capistrano-bundler', require: false
    gem 'capistrano3-puma',   require: false
end

group :production do
    gem 'puma',                 '2.7.1'
    # gem 'puma_worker_killer'
end

gem 'twitter-bootswatch-rails', '~> 3.3.2'
gem 'twitter-bootswatch-rails-helpers'

gem 'less-rails'
gem 'jquery-rails'
gem 'slim'
gem 'execjs'
gem 'turbolinks'
gem 'therubyracer'

gem 'rails_autolink'
gem 'youtube_it'
gem 'rest-client'
gem 'nokogiri'
gem 'awesome_print'
gem 'quiet_assets'

gem 'devise'
gem 'mongoid'
gem 'newrelic_rpm'
```

**Comment by kriansa** [comment]
Hey @sheharyarn, downgrading fixed it for you? Did you tried Ruby 2.2.2?

**Comment by sheharyarn** [comment]
@kriansa Not completely, but it helped. It's still a very small VPS (with only 512mb of RAM) and my app is memory-intensive. It's crashed only 2 times since downgrading. I've not tried __Ruby 2.2.2__ yet, but I've heard it fixes a lot of the memory issues.

**Comment by SuperMasterBlasterLaser** [comment]
@kriansa  @sheharyarn  This crash still happens on ruby 2.2.2

**Comment by raldred** [comment]
I'm also getting silent crashes on Heroku using Puma 2.14.0 with Ruby 2.2.2.
Mine is not consistent like yours, it's rather random infact.

Although I'm at a loss as to how to debug due to lack of error logging when workers & threads die or become blocked. The only info I have is a ton of H12 errors. A restart of the app server usually resolves it for a while. NewRelic reveals nothing sinister either.

I have 4 dynos each with 2 workers and 3 threads.

**Comment by evanphx** [comment]
Please update to the latest release of puma and try ruby 2.3.0. Most users have said that fixes these kinds of issues.
