### ISSUE TITLE
How to: Restart Puma if Database Connection Drops?

### ISSUE THREAD

**Issue by pctj101** [puma/puma#595]
Last night, for whatever reason, my Puma's mysql connection went away.  In checking, it was probably a temporary say 5 minute problem.  However, every request from that moment forward resulted in this error:

could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)

Is there a way in Puma to detect this kind of problem and restart the server?  Restarting the server to re-initiate the connection to mysql worked for me.  However, I could totally see perhaps it being a rails connection pool problem.  

Since puma is threading and so forth, and I'm not sure if puma affects the way database connections are pooled/reconnected, I was thinking this could be my first stop for questions before heading over to the rails groups.

Any feedback is welcome!

**Comment by quentindemetz** [comment]
I'm encountering this issue as well. Has anybody managed to mitigate it?

**Comment by evanphx** [comment]
@quentindemetz be sure your connection pool is large enough.

**Comment by inspire22** [comment]
I still get this a few times a day with activerecord/mysql.  Right now I have a cron job checking the logfile for "unable to establish a database connection in 5.000" and restarting the server, but that is not ideal...

Min==max threads == # of db connections in pool

**Comment by toymachiner62** [comment]
This is still an issue. I've experienced this issue for 2 years now and I preiodically have to restart my puma server. I can replicate this in my local server using puma, and when I switch back to webrick, the issue is nonexistant.

**Comment by evanphx** [comment]
@toymachiner62 Can you tell me some specifics about what you see and what settings you're using?

**Comment by toymachiner62** [comment]
Here's a sample project which demonstrates the issue. https://github.com/toymachiner62/devise-connection-failure

Hit an incorrect url and then try to hit a valid url and you should see a database connection error.

**Comment by evanphx** [comment]
This appears to have a pool set to 1, meaning only one connection is allowed. How many threads do you have puma configured for though?

**Comment by evanphx** [comment]
Looks like you're doing it via `rails s`, so the default of 16. That's probably the issue. Why do you have the pool set to 1?

**Comment by toymachiner62** [comment]
I've had my production app with as many as 50 and eventually all the mysql connections all get used up, it just takes longer.

**Comment by evanphx** [comment]
Sounds like the connections aren't being returned to the pool properly...

**Comment by toymachiner62** [comment]
Exactly the problem i've been having for years with my one app running on puma. Seems to be a puma related issue b/c for my production app, when i switch to webrick, i don't have the issue.

**Comment by toymachiner62** [comment]
I can give you access to my production app if you'd like. You can really see it then.

**Comment by nathansamson** [comment]
Hi

I had a similar problem a while ago. Every time my app would crash the
connection was not returned and after 5 crashes (pool size) my app would
hang

I believe my problem went away by adding / modyfing my puma config with the
following settings

before_fork do
>   defined?(ActiveRecord::Base) and
>     ActiveRecord::Base.connection.disconnect!
> end
>
> on_worker_boot do
>   ActiveSupport.on_load(:active_record) do
>     config = ActiveRecord::Base.configurations[Rails.env] ||
>                 Rails.application.config.database_configuration[Rails.env]
>     config['reaping_frequency'] = ENV['DB_REAP_FREQ'] || 10 # seconds
>     config['pool']            =   ENV['DB_POOL'] || 2
>     ActiveRecord::Base.establish_connection(config)
>   end
> end
>

Not sure if that would help though...

I can go look back in my version control to look at the exact changes I
made if this is not enough

Nathan

**Comment by toymachiner62** [comment]
That would be helpful. I actually added a puma config file with this yesterday as well and haven't had any crashes yet, but it hasn't been long enough either.

```ruby
preload_app!

on_worker_boot do
  ActiveSupport.on_load(:active_record) do
    ActiveRecord::Base.establish_connection
  end
end

before_fork do
  ActiveRecord::Base.connection_pool.disconnect!
end
```

**Comment by evanphx** [comment]
@toymachiner62 What version of rails? Rails handles all it's own poll management and is supposed to be using rack middleware that returns connections to the pool when a request is finished. If the issue happens because of the bad url, perhaps when an exception occurs rails isn't returning the connection.

As to why it happens on puma and not webrick, thats certainly a good question. Webrick spins up a new Thread for every new connection, so perhaps there is something with the thread locals...

**Comment by toymachiner62** [comment]
I've had the problem since rails 3.1 and now i'm on 4.1.8

**Comment by evanphx** [comment]
@tenderlove any thoughts on this?

**Comment by toymachiner62** [comment]
Here's some questions i've asked over the years without any real luck. http://stackoverflow.com/search?q=user%3A222403+puma

**Comment by nathansamson** [comment]
This was the fix. The upgrade to puma 2.9 was probably irrelavant
[fix.txt](https://github.com/puma/puma/files/89263/fix.txt)

before this change I constantly had problems, afterwards no issues anymore. I don't have a good explanation why this would fix that issue but for me it did...

**Comment by evanphx** [comment]
Ok, looking at the code that is supposed to handle this (https://github.com/rails/rails/blob/4-1-stable/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb) I see it in your backtrace here (http://stackoverflow.com/questions/27801185/activerecordconnectiontimeouterror-could-not-obtain-a-database-connection-wit).

Because it's using the `BodyProxy` hack, if for some reason the body is discarded higher up the middleware stack, the connection won't be returned to the pool.

I wonder slightly why airbrake and dragonfly are so low in the middleware stack, they're actually below the connection pooler code. Meaning if airbrake accesses the database, the connection won't be returned back into the pool!

Do you know if airbrake or dragonfly might be accessing the database?

**Comment by toymachiner62** [comment]
Airbrake does not access the database, but i'm storing images in my database. Not sure if dragonfly directly touches the db or not. 

However I have had this error since before I had integrated dragonfly into my app.

**Comment by matthewd** [comment]
From memory, the AR connection pool reaper got better at reclaiming connections from dead threads in 4.2. That should at least address the problem when the DB connection pool is larger than the puma worker pool -- even if every worker thread (including idle ones) ends up holding a connection somehow.

**Comment by evanphx** [comment]
@toymachiner62 are you using `Rack::Timeout` and do you have many timed out requests?

**Comment by toymachiner62** [comment]
I'm not explicitly using `Rack::Timeout`. I'm not familiar with it.

**Comment by evanphx** [comment]
@toymachiner62 what version of airbrake are you using? This fix (https://github.com/airbrake/airbrake/commit/21bdff4552d1befba6b87e6400ff595c33710672) is extremely important and might be the cause of the issue. Are you using a version of airbrake with that added line?

**Comment by toymachiner62** [comment]
Looks like that fix was made in V3.0.6 and i'm on `gem 'airbrake', '~> 4.1'`

**Comment by matthewd** [comment]
@toymachiner62 are you able to try 4.2? Or attempt to backport https://github.com/rails/rails/pull/14360?

**Comment by evanphx** [comment]
Ok, so I booted up https://github.com/toymachiner62/devise-connection-failure and update it to the latest puma. I don't see a connection error when accessing `localhost:3000/asdf` or any other urls. Could the issue be fixed in the newest puma? Can you try to replicate the issue after running `bundle update puma`?

**Comment by toymachiner62** [comment]
It seems that updating puma to 2.15.x resolves the issue. I have a reproducible test case on my dev app that I could trigger the error every time (even after upgrading to rails 4.2.x). Now that my puma has been upgraded my test case does not trigger the connection timeout. Thanks for the help on this guys.

**Comment by evanphx** [comment]
@toymachiner62 wonderful! I'm going to do a little investigate to figure out WHY the upgrade fixed the issue as well.

**Comment by toymachiner62** [comment]
Looks like my previous version of puma was 2.10 if that helps.

**Comment by oozzal** [comment]
@evanphx The issue still persists for me. I'm on `jruby-9.1.2.0` and `puma-3.4.0`. What about you @toymachiner62 ?

**Comment by toymachiner62** [comment]
I'm not on puma 3.x but ever since upgrading to puma 2.15.x I've not had an issue ever.
